name: makefile-test
on:
  push:
    branches:
      - feature/example-program-completion
      - testing
  pull_request:

permissions:
  contents: read

jobs:
  makefile-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
          cache: false
      - run: make run_example
